# Generated by Django 5.1.1 on 2024-10-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emp',
            name='project',
            field=models.CharField(default='', max_length=200),
        ),
    ]
