# Generated by Django 5.1.1 on 2024-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_attendance_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
