# Generated by Django 5.1.1 on 2024-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_emp_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='overtime_score',
            field=models.FloatField(default=0),
        ),
    ]
