# Generated by Django 5.1.1 on 2024-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_performance_overtime_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='attendance_score',
            field=models.FloatField(default=0, help_text='Attendance score as a percentage.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='overall_score',
            field=models.FloatField(default=0, help_text='The overall performance score, calculated.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='overtime_score',
            field=models.FloatField(default=0, help_text='Overtime score as a percentage.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='project_score',
            field=models.FloatField(default=0, help_text='Project score as a percentage.'),
        ),
    ]
