# Generated by Django 5.1.1 on 2024-11-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_performance_attendance_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='overall_score',
        ),
        migrations.AddField(
            model_name='performance',
            name='meeting_score',
            field=models.FloatField(default=0, help_text='Score based on average meeting performance.'),
        ),
        migrations.AddField(
            model_name='performance',
            name='publication_score',
            field=models.FloatField(default=0, help_text='Score based on publications (3 points per paper/article).'),
        ),
        migrations.AddField(
            model_name='performance',
            name='total_score',
            field=models.FloatField(default=0, help_text='The total performance score.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='attendance_score',
            field=models.FloatField(default=0, help_text='Score based on attendance (1 point per day present).'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='overtime_score',
            field=models.FloatField(default=0, help_text='Score based on overtime (calculated in hours).'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='project_score',
            field=models.FloatField(default=0, help_text='Score based on project completion (5 points per project).'),
        ),
    ]
