# Generated by Django 5.1.1 on 2024-11-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_remove_performance_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='meetings',
            field=models.IntegerField(default=0),
        ),
    ]
