# Generated by Django 5.1.1 on 2024-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='attendance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='meeting_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='overtime_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='project_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='publication_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
